---
EnableDefaultLinters: false
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
inherit_gem:  
  erblint-github:
    - config/accessibility.yml
linters:
  GitHub::Accessibility::NoTitleAttribute:
    exclude:
      - 'app/views/layouts/application.html.erb'
      - 'app/views/catalog/_index_default.html.erb'
      - 'app/views/catalog/_show_header_default.html.erb'
      - 'app/views/catalog/_show_main_content.html.erb'
      - 'app/views/catalog/stackmap.html.erb'
      - 'app/views/shared/_account.html.erb'

  GitHub::Accessibility::NoAriaLabelMisuse:
    exclude:
      - 'app/views/shared/_account.html.erb'
      - 'app/views/catalog/stackmap.html.erb'
      - 'app/views/shared/_footer.html.erb'
