name: orangelight
services:
  orangelight_test_solr:
    type: solr:custom
    overrides:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.0
      command: server/scripts/lando-start.sh
    portforward: true
    core: orangelight-core-test
    config:
      dir: "solr/conf"
  orangelight_small_test_solr:
    type: solr:custom
    overrides:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.0
      command: server/scripts/lando-start.sh
    portforward: true
    core: orangelight-core-small-test
    config:
      dir: "solr/conf"
  orangelight_development_solr:
    type: solr:custom
    overrides:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.0
      command: server/scripts/lando-start.sh
    portforward: true
    core: orangelight-core-dev
    config:
      dir: "solr/conf"
  orangelight_database:
    type: postgres:15
    portforward: true
  orangelight_redis:
    type: redis:7
    portforward: true
proxy:
  orangelight_test_solr:
    - orangelight.test.solr.lndo.site:8983
  orangelight_small_test_solr:
    - orangelight.test.small.solr.lndo.site:8983
  orangelight_development_solr:
    - orangelight.dev.solr.lndo.site:8983
