name: orangelight
services:
  orangelight_test_solr:
    type: solr:custom
    overrides:
      image: pulibrary/ci-solr:8.4-v1.0.0
      command: server/scripts/lando-start.sh
    portforward: true
    core: orangelight-core-test
    config:
      dir: "solr/conf"
  orangelight_development_solr:
    type: solr:custom
    overrides:
      image: pulibrary/ci-solr:8.4-v1.0.0
      command: server/scripts/lando-start.sh
    portforward: true
    core: orangelight-core-dev
    config:
      dir: "solr/conf"
  orangelight_database:
    type: postgres:13
    portforward: true
  orangelight_redis:
    type: redis:6.0.16
    portforward: true
proxy:
  orangelight_test_solr:
    - orangelight.test.solr.lndo.site:8983
  orangelight_development_solr:
    - orangelight.dev.solr.lndo.site:8983
