inherit_from: .rubocop_todo.yml

require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/deploy.rb'
    - 'config/initializers/blacklight_url_helper_behavior.rb'
    - 'config/environments/**/*'
    - 'spec/views/catalog/_show_availability_sidebar.html.erb_spec.rb'
    - 'node_modules/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/models/requests/illiad_metadata/article_express.rb'
    - 'app/models/concerns/blacklight/document/json_ld.rb'
    - 'app/models/requests/solr_open_url_context.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/views/catalog/_document_default.atom.builder'
    - 'config/routes.rb'
    - 'config/deploy/staging.rb'
    - 'config/deploy/alma-qa.rb'
    - 'config/deploy/qa.rb'
    - 'lib/tasks/browse.rake'
    - 'lib/tasks/pulsearch.rake'
    - 'spec/**/*'
    - 'lib/tasks/server.rake'

Metrics/BlockNesting:
  Exclude:
    - 'app/helpers/advanced_helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/models/solr_document.rb'
    - 'app/services/online_holdings_markup_builder.rb'
    - 'app/services/holding_requests_adapter.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'spec/mailers/previews/*'
    - 'lib/orangelight/browse_lists/call_number_csv.rb'
    - 'app/models/requests/request.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'lib/orangelight/browse_lists/call_number_csv.rb'
    - 'app/services/bibdata.rb'
    - 'app/models/requests/router.rb'

Layout/LineLength:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'spec/system/searching_spec.rb'
    - 'spec/models/solr_document_spec.rb'
    - 'spec/controllers/bookmarks_controller_spec.rb'
    - 'spec/features/availability_spec.rb'
    - 'spec/helpers/holding_block_spec.rb'
    - 'spec/helpers/blacklight_helper_spec.rb'
    - 'spec/helpers/requests/application_helper_spec.rb'
    - 'spec/services/online_holdings_markup_builder_spec.rb'
    - 'spec/services/holding_requests_adapter_spec.rb'
    - 'app/repositories/course_reserve_repository.rb'
    - 'spec/mailers/previews/*'
    - 'spec/lib/orangelight/browse_lists/call_number_csv_spec.rb'

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/models/concerns/blacklight/document/ris.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/models/requests/illiad_metadata/metadata.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/online_holdings_markup_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'spec/features/course_reserves_spec.rb'
    - 'spec/repositories/course_reserve_repository_spec.rb'
    - 'spec/requests/course_reserve_spec.rb'
    - 'lib/tasks/server.rake'
    - 'lib/orangelight/browse_lists.rb'
    - 'lib/orangelight/browse_lists/call_number_csv.rb'
    - 'spec/mailers/previews/*'

Metrics/ParameterLists:
  Exclude:
    - 'app/models/requests/illiad_metadata/metadata.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/concerns/blacklight/document/json_ld.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'lib/orangelight/browse_lists/call_number_csv.rb'
    - 'app/models/requests/router.rb'

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
    - 'config/deploy/alma-production.rb'
    - 'config/deploy/alma-qa.rb'

Performance/RegexpMatch:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
# TODO: Fix
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/online_holdings_markup_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'

Rails/TimeZone:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'spec/helpers/locations_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/catalog_helper_spec.rb'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

# TODO: Fix all below here
Style/GuardClause:
  Exclude:
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/document/email.rb'
    - 'app/models/concerns/blacklight/document/ris.rb'

Rails/RakeEnvironment:
  Enabled: false

Rails/ContentTag:
  Enabled: false

Rails/ApplicationMailer:
  Exclude:
    - 'app/models/record_mailer.rb'
