require: rubocop-rspec
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  UseCache: false
  DisplayCopNames: true
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/deploy.rb'
    - 'config/initializers/blacklight_url_helper_behavior.rb'
    - 'config/environments/**/*'
    - 'spec/views/catalog/_show_availability_sidebar.html.erb_spec.rb'
    - 'node_modules/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/feedback_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/blacklight_url_helper.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/models/user.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/document/ris.rb'
    - 'app/services/linked_document_resolver.rb'
    - 'config/initializers/requests_initializer.rb'
    - 'lib/orangelight/bibdata.rb'
    - 'lib/orangelight/browse_lists.rb'
    - 'lib/orangelight/voyager_account.rb'
    - 'lib/orangelight/voyager_patron_client.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'app/services/online_holdings_markup_builder.rb'
    - 'app/helpers/catalog_helper.rb'
    - 'app/controllers/catalog_controller.rb'

Metrics/BlockNesting:
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'

Metrics/ClassLength:
  Exclude:
  - 'app/controllers/account_controller.rb'
  - 'app/controllers/catalog_controller.rb'
  - 'lib/orangelight/voyager_patron_client.rb'
  - 'app/services/holding_requests_builder.rb'
  - 'app/services/physical_holdings_markup_builder.rb'
  - 'app/services/online_holdings_markup_builder.rb'
  - 'app/services/holding_requests_adapter.rb'
  - 'app/controllers/orangelight/browsables_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/blacklight_url_helper.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/document/ris.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'lib/orangelight/browse_lists.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/document/ris.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'config/initializers/borrow_direct.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/blacklight_folders.rb'
    - 'config/initializers/requests_initializer.rb'
    - 'config/sitemap.rb'
    - 'lib/orangelight/browse_lists.rb'
    - 'lib/orangelight/voyager_patron_client.rb'
    - 'spec/**/*'
    - 'app/views/catalog/_document_default.atom.builder'
    - 'lib/tasks/pulsearch.rake'
    - 'lib/tasks/server.rake'
    - '**/Gemfile'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/helpers/catalog_helper.rb'
    - 'lib/orangelight/middleware/invalid_parameter_handler.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/feedback_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/blacklight_url_helper.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/document/ris.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'config/initializers/requests_initializer.rb'
    - 'lib/orangelight/bibdata.rb'
    - 'lib/orangelight/browse_lists.rb'
    - 'lib/orangelight/voyager_account.rb'
    - 'lib/orangelight/voyager_patron_client.rb'
    - 'spec/features/course_reserves_spec.rb'
    - 'spec/requests/course_reserve_spec.rb'
    - 'spec/repositories/course_reserve_repository_spec.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'app/services/online_holdings_markup_builder.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'lib/orangelight/browse_lists.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/blacklight_url_helper.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'lib/orangelight/browse_lists.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/requests/request_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/models/voyager_patron_client_spec.rb'
    - 'spec/services/holding_requests_adapter_spec.rb'

Style/AsciiComments:
  Exclude:
    - 'lib/orangelight/string_functions.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/helpers/scsb_items_helper_spec.rb'

Naming/FileName:
  Exclude:
    - 'lib/omniauth/strategies/omniauth-barcode.rb'

Style/MutableConstant:
  Exclude:
    - 'config/initializers/borrow_direct.rb'
    - 'config/initializers/locations_initializer.rb'


Naming/PredicateName:
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'lib/orangelight/voyager_account.rb'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/RaiseArgs:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'

Style/HashSyntax:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'spec/helpers/blacklight_helper_spec.rb'

Rails/TimeZone:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'app/services/online_holdings_markup_builder.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/requests/**/*'

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/blacklight_advanced_search/parsing_nesting_spec.rb'
    - 'spec/views/catalog/_sort_and_per_page.html.erb_spec.rb'

Rails/UnknownEnv:
  Exclude:
    - 'app/controllers/application_controller.rb'

Rails/UnknownEnv:
  Environments:
    - staging
    - production
    - development
    - test
