require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/deploy.rb'
    - 'config/initializers/blacklight_url_helper_behavior.rb'
    - 'config/environments/**/*'
    - 'spec/views/catalog/_show_availability_sidebar.html.erb_spec.rb'
    - 'node_modules/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/account_controller.rb:'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'lib/orangelight/browse_lists.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/views/catalog/_document_default.atom.builder'
    - 'app/helpers/application_helper.rb'
    - 'config/routes.rb'
    - 'config/deploy/staging.rb'
    - 'lib/tasks/browse.rake'
    - 'lib/tasks/pulsearch.rake'
    - 'lib/orangelight/browse_lists.rb'
    - 'spec/**/*'

Metrics/BlockNesting:
  Exclude:
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'lib/orangelight/voyager_patron_client.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'lib/orangelight/browse_lists.rb'

Metrics/LineLength:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'spec/features/searching_spec.rb'
    - 'spec/models/solr_document_spec.rb'
    - 'spec/controllers/bookmarks_controller_spec.rb'
    - 'spec/views/catalog/umlaut_services_spec.rb'
    - 'spec/helpers/holding_block_spec.rb'
    - 'spec/helpers/blacklight_helper_spec.rb'
    - 'spec/services/online_holdings_markup_builder_spec.rb'
    - 'spec/services/holding_requests_adapter_spec.rb'
    - 'app/repositories/course_reserve_repository.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/models/concerns/blacklight/document/ris.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/account_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/online_holdings_markup_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'spec/features/course_reserves_spec.rb'
    - 'spec/repositories/course_reserve_repository_spec.rb'
    - 'spec/requests/course_reserve_spec.rb'
    - 'lib/tasks/server.rake'
    - 'lib/orangelight/browse_lists.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'lib/orangelight/browse_lists.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/concerns/blacklight/solr/document/marc.rb'
    - 'app/controllers/orangelight/browsables_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/helpers/facets_helper.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/physical_holdings_markup_builder.rb'
    - 'lib/orangelight/browse_lists.rb'

# Look into this
Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

Naming/PredicateName:
  Exclude:
    - 'lib/orangelight/voyager_account.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Enabled: false

# TODO: Fix
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/blacklight_advanced_search/parsing_nesting_spec.rb'
    - 'spec/views/catalog/_sort_and_per_page.html.erb_spec.rb'

# Should fix
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/services/holding_requests_builder.rb'
    - 'app/services/online_holdings_markup_builder.rb'
    - 'app/services/physical_holdings_markup_builder.rb'

Rails/TimeZone:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'spec/helpers/locations_spec.rb'

# Should fix
Style/GuardClause:
  Exclude:
    - 'app/controllers/account_controller.rb'
    - 'app/controllers/concerns/orangelight/catalog.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/helpers/advanced_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/blacklight_helper.rb'
    - 'app/models/concerns/blacklight/document/dublin_core.rb'
    - 'app/models/concerns/blacklight/document/email.rb'
    - 'app/models/concerns/blacklight/document/ris.rb'

# TODO: Fix
Style/Next:
  Enabled: false
