{
  'responseHeader'=>{
    'status'=>0,
    'QTime'=>34,
    'params'=>{
      'facet'=>'true',
      'fl'=>'id',
      'indent'=>'true',
      'q'=>'*:*',
      'facet.limit'=>'-1',
      'facet.field'=>'lc_rest_facet',
      'wt'=>'ruby'}},
  'response'=>{'numFound'=>142106,'start'=>0,'docs'=>[
      {
        'id'=>'968483'},
      {
        'id'=>'19148'},
      {
        'id'=>'1789917'},
      {
        'id'=>'2085989'},
      {
        'id'=>'4826705'},
      {
        'id'=>'508885'},
      {
        'id'=>'455677'},
      {
        'id'=>'7002836'},
      {
        'id'=>'2912718'},
      {
        'id'=>'2948361'}]
  },
  'facet_counts'=>{
    'facet_queries'=>{},
    'facet_fields'=>{
      'lc_rest_facet'=>[
        'A - General Works',1,
        'AC - Collections Works',655,
        'AE - Encyclopedias',46,
        'AG - General Reference Works',31,
        'AI - Indexes',30,
        'AM - Museums',41,
        'AN - Newspapers',4,
        'AP - Periodicals',168,
        'AS - Academies & Learned Societies',175,
        'AY - Yearbooks, Almanacs, Directories',34,
        'AZ - History of Scholarship & Learning',17,
        'B - Philosophy, Psychology, Religion',395,
        'BC - Logic',11,
        'BD - Speculative Philosophy',47,
        'BF - Psychology',424,
        'BH - Aesthetics',26,
        'BJ - Ethics',80,
        'BL - Religions (General)',397,
        'BM - Judaism',280,
        'BP - Islam, Bahaism, Theosophy, etc.',129,
        'BQ - Buddhism',256,
        'BR - Christianity',226,
        'BS - The Bible',388,
        'BT - Doctrinal Theology',66,
        'BV - Practical Theology',88,
        'BX - Christian Denominations',264,
        'C - Historical Sciences (Archaeology, Genealogy)',1,
        'CB - History of Civilization',51,
        'CC - Archaeology',21,
        'CD - Diplomatics',121,
        'CE - Technical Chronology',19,
        'CJ - Numismatics',412,
        'CN - Inscriptions',144,
        'CR - Heraldry',20,
        'CS - Genealogy',77,
        'CT - Biography',201,
        'D - World History',400,
        'DA - Great Britain (History)',295,
        'DB - Austria, Liechtenstein, Czech Rep., Hungary, Slovakia (History)',29,
        'DC - France (History)',152,
        'DD - Germany (History)',73,
        'DE - Greco-Roman World (History)',51,
        'DF - Greece (History)',216,
        'DG - Italy (History)',276,
        'DH - Low Countries (History)',10,
        'DJ - Netherlands (History)',8,
        'DJK - Eastern Europe (History)',2,
        'DK - Russia. Former Soviet Republics. Poland (History)',243,
        'DL - Scandinavia (History)',22,
        'DP - Spain. Portugal (History)',63,
        'DQ - Switzerland (History)',5,
        'DR - Balkan Peninsula (History)',61,
        'DS - Asia (History)',2166,
        'DT - Africa (History)',218,
        'DU - Oceania (History)',38,
        'DX - Gypsies (History)',4,
        'E - History of the Americas (General)',1274,
        'F - History of the Americas (Local)',862,
        'G - Geography, Anthropology, Recreation',1025,
        'GA - Mathematical Geography, Cartography',46,
        'GB - Physical Geography',131,
        'GC - Oceanography',33,
        'GE - Environmental Sciences',54,
        'GF - Human Ecology, Anthropogeography',20,
        'GN - Anthropology',108,
        'GR - Folklore',73,
        'GT - Manners & Customs',70,
        'GV - Recreation. Leisure',472,
        'H - Social Sciences',130,
        'HA - Statistics',485,
        'HB - Economic Theory, Demography',479,
        'HC - Economic History & Conditions',436,
        'HD - Industries, Land use, Labor',818,
        'HE - Transportation & Communications',159,
        'HF - Commerce',487,
        'HG - Finance',405,
        'HJ - Public Finance',108,
        'HM - Sociology',201,
        'HN - Social History & Conditions',193,
        'HQ - The Family, Marriage, Woman',523,
        'HS - Societies',24,
        'HT - Communities, Classes, Races',216,
        'HV - Social Pathology, Social & Public Welfare, Criminology',335,
        'HX - Socialism, Communism, Anarchism',62,
        'J - Political Science',23,
        'JA - Political Science',66,
        'JC - Political Theory',177,
        'JF - Political Institutions',54,
        'JK - Political Institutions (U.S.)',284,
        'JL - Political Institutions (Canada, Latin America)',37,
        'JN - Political Institutions (Europe)',73,
        'JQ - Political Institutions (Asia, Africa, Australia, Pacific Area)',119,
        'JS - Local Government',46,
        'JV - Colonies & Colonization, Emigration & Immigration',73,
        'JX - International Law',235,
        'JZ - International Relations',56,
        'K - Law',140,
        'KBP - Islamic Law',4,
        'KBR - Canon Law',1,
        'KD - Law of England & Wales',11,
        'KDK - Law of Ireland (EIRE)',1,
        'KDZ - Law of America, North America',2,
        'KE - Law of Canada',2,
        'KF - Law of the U.S.',311,
        'KG - Law of Latin America, Mexico, Central America, West Indies, Caribbean',4,
        'KJ - Law of Europe',1,
        'KJA - Roman Law',16,
        'KJC - Regional Comparative & Uniform Law',6,
        'KJE - Regional Organization & Integration',12,
        'KJV - Law of France',6,
        'KK - Law of Germany',4,
        'KKE - Law of Greece',2,
        'KKF - Law of Hungary',1,
        'KKH - Law of Italy',4,
        'KKT - Law of Spain',1,
        'KKX - Law of Turkey',1,
        'KKY - Law of Ukraine',1,
        'KL - History of Law, The Ancient Orient',3,
        'KLA - Law of Russia, Soviet Union',6,
        'KLB - Law of Russia (Federation)',14,
        'KLF - Law of Belarus',1,
        'KLP - Law of Ukraine',1,
        'KMP - Law of Lebanon',1,
        'KNN - Law of China',6,
        'KNP - Law of Taiwan',5,
        'KNR - Law of Hong Kong',1,
        'KNX - Law of Japan',12,
        'KPA - Law of Korea',10,
        'KZ - Law of Nations',41,
        'L - Education',34,
        'LA - History of Education',83,
        'LB - Theory & Practice of Education',252,
        'LC - Special Aspects of Education',98,
        'LD - Individual Educational Institutions (U.S.)',78,
        'LE - Individual Educational Institutions: America (except U.S.)',1,
        'LF - Individual Educational Institutions: Europe',16,
        'LG - Individual Educational Institutions: Asia, Africa, Oceania',12,
        'LH - College & School Magazines & Papers',6,
        'LT - Textbooks',10,
        'M - Music',1378,
        'ML - Literature on Music',1924,
        'MT - Musical Instruction & Study',175,
        'N - Fine Arts',1076,
        'NA - Architecture',1498,
        'NB - Sculpture',121,
        'NC - Drawing, Design, Illustration',296,
        'ND - Painting',680,
        'NE - Print Media',311,
        'NK - Decorative Arts',322,
        'NX - Arts in General',129,
        'P - Language & Literature',196,
        'PA - Greek & Latin Language & Literature',1759,
        'PB - Modern Language, Celtic Languages',19,
        'PC - Romanic Languages',252,
        'PD - Germanic Languages',12,
        'PE - English Languages',208,
        'PF - West Germanic Languages',122,
        'PG - Slavic, Baltic, Albanian Languages, Russian Language & Literature',321,
        'PH - Uralic & Basque Languages',8,
        'PJ - Oriental Languages & Literature',285,
        'PK - Indo-Iranian Languages & Literature',123,
        'PL - Languages & Literatures of Eastern Asia, Africa, Oceania',2304,
        'PM - Hyperborean, Indian & Artificial Languages',21,
        'PN - Literature (General)',1645,
        'PQ - French, Italian, Spanish & Portuguese Literature',797,
        'PR - English Literature',1839,
        'PS - American Literature',1766,
        'PT - Germanic & Scandinavian Literatures',400,
        'PZ - Children\'s Literature',824,
        'Q - Science',396,
        'QA - Mathematics',1236,
        'QB - Astronomy',248,
        'QC - Physics',1077,
        'QD - Chemistry',358,
        'QE - Geology',714,
        'QH - Natural History, Biology',584,
        'QK - Botany',116,
        'QL - Zoology',824,
        'QM - Human Anatomy',21,
        'QP - Physiology',277,
        'QR - Microbiology',61,
        'R - Medicine',166,
        'RA - Public Aspects of Medicine',207,
        'RB - Pathology',20,
        'RC - Internal Medicine',250,
        'RD - Surgery',10,
        'RE - Ophthalmology',6,
        'RF - Otorhinolaryngology',1,
        'RG - Gynecology & Obstetrics',20,
        'RJ - Pediatrics',28,
        'RL - Dermatology',4,
        'RM - Therapeutics, Pharmacology',63,
        'RS - Pharmacy & Materia Medica',39,
        'RT - Nursing',9,
        'RZ - Other Systems of Medicine',1,
        'S - Agriculture',66,
        'SB - Plant Culture',160,
        'SD - Forestry',17,
        'SF - Animal Culture',76,
        'SH - Aquaculture',232,
        'SK - Hunting Sports',195,
        'T - Technology',180,
        'TA - Engineering, Civil Engineering',472,
        'TC - Hydraulic Engineering',48,
        'TD - Environmental Technology',169,
        'TE - Highway Engineering',12,
        'TF - Railroad Engineering & Operation',9,
        'TG - Bridge Engineering',17,
        'TH - Building Construction',88,
        'TJ - Mechanical Engineering & Machinery',203,
        'TK - Electrical Engineering, Nuclear Engineering',466,
        'TL - Motor Vehicles, Aeronautics, Astronautics',235,
        'TN - Mining Engineering',164,
        'TP - Chemical Technology',199,
        'TR - Photography',1755,
        'TS - Manufactures',161,
        'TT - Handicrafts',28,
        'TX - Home Economics',54,
        'U - Military Science',77,
        'UA - Armies',62,
        'UB - Military Administration',20,
        'UC - Maintenance & Transportation',7,
        'UD - Infantry',2,
        'UE - Cavalry, Armor',2,
        'UF - Artillery',5,
        'UG - Military Engineering, Air Forces, Military Astronautics',37,
        'UH - Other Military Services',6,
        'V - Naval Science',12,
        'VA - Navies',8,
        'VB - Naval Administration',3,
        'VE - Marines',1,
        'VG - Minor Services of Navies',1,
        'VK - Navigation, Merchant Marine',27,
        'VM - Naval Architecture, Marine Engineering',30,
        'Z - Bibliography, Library Science, Information Resources',4382,
        'ZA - Information Science',9]},
    'facet_dates'=>{},
    'facet_ranges'=>{}}}
