defaults: &defaults
  host: 'localhost'
  port: '6379'
  db: <%= ENV['OL_REDIS_DB'] || 7 %>
development:
  <<: *defaults
  host: <%= ENV['lando_orangelight_redis_conn_host'] %>
  port: <%= ENV['lando_orangelight_redis_conn_port'] %>
test:
  <<: *defaults
  host: <%= ENV['lando_orangelight_redis_conn_host'] %>
  port: <%= ENV['lando_orangelight_redis_conn_port'] %>
production:
  <<: *defaults
  host: <%= ENV['OL_REDIS_HOST'] %>
  port: <%= ENV['OL_REDIS_PORT'] || '6379' %>
staging:
  <<: *defaults
  host: <%= ENV['OL_REDIS_HOST'] %>
  port: <%= ENV['OL_REDIS_PORT'] || '6379' %>
qa:
  <<: *defaults
  host: <%= ENV['OL_REDIS_HOST'] %>
  port: <%= ENV['OL_REDIS_PORT'] || '6379' %>
