# Configuration file for generation robots.txt
defaults: &defaults
  sitemap_url: https://catalog.princeton.edu/sitemap.xml.gz
  disallowed_paths:
    - '/?q=*'
    - '/?f*'
    - '/*?q=*'
    - '/*?f*'
    - '/requests'
    - '/browse'
    - '/browse/call_numbers'
    - '/browse/names'
    - '/browse/name_titles'
    - '/browse/subjects'
    - '/catalog.atom'
    - '/catalog.rss'
    - '/catalog/*/'
    - '/catalog/endnote'
    - '/catalog/opensearch'
    - '/catalog/range_limit'
    - '/catalog/email'
    - '/catalog/sms'
    - '/catalog/citation'
    - '/bookmarks'
    - '/users'
    - '/cgi-bin'
    - '/account'
    - '/borrow-direct'
    - '/thumbnail'
    - '/unapi'
    - '/404'
    - '/422'
    - '/500'
    - '/search_history'
    - '/suggest'
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
