name: Adds all maintenance issues to DACS maintenance board
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd
        with:
          project-url: https://github.com/orgs/pulibrary/projects/55
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: maintenance
